version: "3.8"

services:
  gateway:
    image: http-gateway
    restart: always
    environment:
      - LOGGING=true
      - SECRET=1234
      - PORT=8080
      - AUTH_KEY=1234
      - TAILSCALE_HOSTNAME=http-gateway
    ports:
      - "80:80/tcp"
    logging:
      options:
        max-size: "1024m"
        max-file: "5"